# Generated by Django 5.1.7 on 2025-04-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatoMercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('habilidades_demandadas', models.TextField()),
                ('tendencias_region', models.TextField()),
                ('tendencias_industria', models.TextField()),
            ],
        ),
    ]
