# Generated by Django 5.1.7 on 2025-04-15 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis_mercado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OfertaEmpleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('ubicacion', models.CharField(max_length=255)),
                ('salario', models.FloatField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField()),
                ('datomercado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analisis_mercado.datomercado')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obtencion_datos_mercado.habilidad')),
                ('oferta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obtencion_datos_mercado.ofertaempleo')),
            ],
            options={
                'unique_together': {('oferta', 'habilidad')},
            },
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='habilidades',
            field=models.ManyToManyField(through='obtencion_datos_mercado.OfertaHabilidad', to='obtencion_datos_mercado.habilidad'),
        ),
    ]
